"""URETILDI: agent/build_catalog.py. Elle duzenleme; yeniden uret."""
CATALOG_DATA = [
    {'name': 'nmap', 'domain': 'recon-scan', 'risk': 'low', 'params': ('hedef', 'secenekler')},
    {'name': 'rustscan', 'domain': 'recon-scan', 'risk': 'low', 'params': ('hedef', 'secenekler')},
    {'name': 'masscan', 'domain': 'recon-scan', 'risk': 'low', 'params': ('hedef', 'secenekler')},
    {'name': 'netdiscover', 'domain': 'recon-scan', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'arp-scan', 'domain': 'recon-scan', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'fping', 'domain': 'recon-scan', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'wireshark', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('dosya', 'filtre')},
    {'name': 'tshark', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('dosya', 'secenekler')},
    {'name': 'tcpdump', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'bettercap', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('arayuz', 'komutlar')},
    {'name': 'ettercap', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'mitmproxy', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'responder', 'domain': 'traffic-mitm', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'theHarvester', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'kaynaklar', 'limit')},
    {'name': 'maltego', 'domain': 'osint', 'risk': 'low', 'params': ('entity', 'transforms')},
    {'name': 'amass', 'domain': 'osint', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'subfinder', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'secenekler')},
    {'name': 'spiderfoot', 'domain': 'osint', 'risk': 'low', 'params': ('hedef', 'secenekler')},
    {'name': 'recon-ng', 'domain': 'osint', 'risk': 'low', 'params': ('komutlar', 'workspace')},
    {'name': 'sherlock', 'domain': 'osint', 'risk': 'low', 'params': ('kullanici',)},
    {'name': 'shodan', 'domain': 'osint', 'risk': 'low', 'params': ('komut', 'sorgu')},
    {'name': 'dnsrecon', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'secenekler')},
    {'name': 'dnsenum', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'secenekler')},
    {'name': 'fierce', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'secenekler')},
    {'name': 'whois', 'domain': 'osint', 'risk': 'low', 'params': ('domain',)},
    {'name': 'dig', 'domain': 'osint', 'risk': 'low', 'params': ('domain', 'tip')},
    {'name': 'host', 'domain': 'osint', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'burpsuite', 'domain': 'web', 'risk': 'medium', 'params': ('degisiklik', 'eylem', 'istek')},
    {'name': 'zap', 'domain': 'web', 'risk': 'medium', 'params': ('mod', 'secenekler', 'url')},
    {'name': 'nuclei', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'gobuster', 'domain': 'web', 'risk': 'medium', 'params': ('mod', 'url', 'uzantilar', 'wordlist')},
    {'name': 'ffuf', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url', 'wordlist')},
    {'name': 'feroxbuster', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'dirsearch', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'dirb', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'nikto', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler',)},
    {'name': 'sqlmap', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'wpscan', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'wfuzz', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'arjun', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'paramspider', 'domain': 'web', 'risk': 'medium', 'params': ('domain', 'secenekler')},
    {'name': 'dalfox', 'domain': 'web', 'risk': 'medium', 'params': ('hedef', 'mod')},
    {'name': 'xsstrike', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'httpx', 'domain': 'web', 'risk': 'medium', 'params': ('liste', 'secenekler')},
    {'name': 'katana', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'whatweb', 'domain': 'web', 'risk': 'medium', 'params': ('secenekler', 'url')},
    {'name': 'metasploit', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('komutlar',)},
    {'name': 'msfvenom', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'searchsploit', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('sorgu',)},
    {'name': 'sliver', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('komutlar',)},
    {'name': 'netexec', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('hedef', 'protokol', 'secenekler')},
    {'name': 'bloodhound-python', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'impacket', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('arac', 'secenekler')},
    {'name': 'secretsdump', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('hedef', 'secenekler')},
    {'name': 'evil-winrm', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'mimikatz', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('komutlar',)},
    {'name': 'rubeus', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('komut', 'secenekler')},
    {'name': 'routersploit', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('modul', 'secenekler')},
    {'name': 'beef', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('eylem', 'payload')},
    {'name': 'enum4linux-ng', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('hedef', 'secenekler')},
    {'name': 'smbclient', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'smbmap', 'domain': 'exploit-ad', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'hydra', 'domain': 'password', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'john', 'domain': 'password', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'hashcat', 'domain': 'password', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'medusa', 'domain': 'password', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'hashid', 'domain': 'password', 'risk': 'high', 'params': ('hash',)},
    {'name': 'aircrack-ng', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'airodump-ng', 'domain': 'wireless', 'risk': 'high', 'params': ('arayuz', 'secenekler')},
    {'name': 'aireplay-ng', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'wifite', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'hcxdumptool', 'domain': 'wireless', 'risk': 'high', 'params': ('arayuz', 'secenekler')},
    {'name': 'kismet', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'reaver', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'mdk4', 'domain': 'wireless', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'volatility3', 'domain': 'forensic-re', 'risk': 'low', 'params': ('dosya', 'eklenti')},
    {'name': 'autopsy', 'domain': 'forensic-re', 'risk': 'low', 'params': ('eylem', 'imaj', 'moduller')},
    {'name': 'sleuthkit', 'domain': 'forensic-re', 'risk': 'low', 'params': ('komut',)},
    {'name': 'binwalk', 'domain': 'forensic-re', 'risk': 'low', 'params': ('dosya', 'secenekler')},
    {'name': 'foremost', 'domain': 'forensic-re', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'ghidra', 'domain': 'forensic-re', 'risk': 'low', 'params': ('eylem', 'secenekler')},
    {'name': 'radare2', 'domain': 'forensic-re', 'risk': 'low', 'params': ('dosya', 'komutlar')},
    {'name': 'gdb', 'domain': 'forensic-re', 'risk': 'low', 'params': ('komutlar',)},
    {'name': 'strings', 'domain': 'forensic-re', 'risk': 'low', 'params': ('dosya', 'secenekler')},
    {'name': 'yara', 'domain': 'forensic-re', 'risk': 'low', 'params': ('hedef', 'kurallar')},
    {'name': 'capa', 'domain': 'forensic-re', 'risk': 'low', 'params': ('dosya',)},
    {'name': 'linpeas', 'domain': 'privesc', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'winpeas', 'domain': 'privesc', 'risk': 'high', 'params': ('secenekler',)},
    {'name': 'shell', 'domain': 'privesc', 'risk': 'high', 'params': ('komut',)},
    {'name': 'fail2ban', 'domain': 'blue-server', 'risk': 'low', 'params': ('komut',)},
    {'name': 'iptables', 'domain': 'blue-server', 'risk': 'low', 'params': ('komutlar',)},
    {'name': 'nftables', 'domain': 'blue-server', 'risk': 'low', 'params': ('eylem', 'ruleset')},
    {'name': 'ufw', 'domain': 'blue-server', 'risk': 'low', 'params': ('komutlar',)},
    {'name': 'auditd', 'domain': 'blue-server', 'risk': 'low', 'params': ('kurallar',)},
    {'name': 'osquery', 'domain': 'blue-server', 'risk': 'low', 'params': ('sorgu',)},
    {'name': 'wazuh', 'domain': 'blue-server', 'risk': 'low', 'params': ('eylem', 'secenekler')},
    {'name': 'suricata', 'domain': 'blue-server', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'snort', 'domain': 'blue-server', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'clamav', 'domain': 'blue-server', 'risk': 'low', 'params': ('komut',)},
    {'name': 'lynis', 'domain': 'blue-server', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'rkhunter', 'domain': 'blue-server', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'chkrootkit', 'domain': 'blue-server', 'risk': 'low', 'params': ('komut',)},
    {'name': 'aide', 'domain': 'blue-server', 'risk': 'low', 'params': ('komut',)},
    {'name': 'ss', 'domain': 'recon-scan', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'trivy', 'domain': 'cloud', 'risk': 'low', 'params': ('hedef', 'hedef_tipi', 'secenekler')},
    {'name': 'prowler', 'domain': 'cloud', 'risk': 'low', 'params': ('saglayici', 'secenekler')},
    {'name': 'scoutsuite', 'domain': 'cloud', 'risk': 'low', 'params': ('saglayici', 'secenekler')},
    {'name': 'kube-hunter', 'domain': 'cloud', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'kube-bench', 'domain': 'cloud', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'docker-bench', 'domain': 'cloud', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'checkov', 'domain': 'cloud', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'tfsec', 'domain': 'cloud', 'risk': 'low', 'params': ('secenekler',)},
    {'name': 'apktool', 'domain': 'mobile-social', 'risk': 'medium', 'params': ('secenekler',)},
    {'name': 'jadx', 'domain': 'mobile-social', 'risk': 'medium', 'params': ('secenekler',)},
    {'name': 'mobsf', 'domain': 'mobile-social', 'risk': 'medium', 'params': ('dosya', 'eylem')},
    {'name': 'gophish', 'domain': 'mobile-social', 'risk': 'medium', 'params': ('eylem', 'parametreler')},
    {'name': 'setoolkit', 'domain': 'mobile-social', 'risk': 'medium', 'params': ('hedef_url', 'modul', 'secenekler')},
]
